### PR TITLE
(ansi-term PR 80): Add "bright" builtin codes and tests.

### PR DESCRIPTION
**Pull request by gierens**
https://github.com/ogham/rust-ansi-term/pull/80

### CODE REVIEW

**Comment by gierens** [comment]
Wait what?!

1. we have duplicate tests, opened an issue for it #13
2. but more importantly why do the same tests fail in the `pull_request` tests fail but not the `push` tests?

**Comment by PThorpe92** [comment]
gahh what is with this test failing.. I ran this PR locally and it passed all tests and didn't break eza... and i cant get any (useful) info from the output of the failed action. Lame. I'll figure it out. The CI looks fine on the other PR's is the problem

**Comment by gierens** [comment]
I rebased it against the current main, maybe that'll change anything.

**Comment by gierens** [comment]
ok, now both test and coverage jobs are failing XD ... that's not really an improvement but at least consistent :D

**Comment by gierens** [comment]
ah wait now it fails locally, too

**Comment by gierens** [comment]
interesting ... i think maybe due to the merge conflict or something maybe both workflows ran with different revisions.

**Comment by gierens** [comment]
Ahhh, ok now I see the error ... there where some missing match cases ... for some reason the merge might have been incomplete and that's why it didn't show up in both workflow runs ... one was working with a different revision. weird!! :D

**Comment by gierens** [comment]
Alright, now it should be ready for review and merging. That was certainly a weird issue. The test output referenced code not actually on the branch. No idea what exactly went wrong there. Must have been something with the merge conflict I had to resolve I guess.

**Review by PThorpe92 — APPROVED** [review]
LGTM

**Comment by PThorpe92** [comment]
Ok I thought i was hallucinating.. cuz none of that code was local on my machine. I did have to update the branch with the syntax fixes that I updated the main branch with to get it to pass tho. 

But either way, this doesn't break Eza

**Pull request merged**
